account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', login, name='login'),
    path('signup/', login, name='login'),
    path('jk34BB23BHddv12HsNNJ/', login_validate, name='login_validate'),
    path('index/', index, name='index'),

    # path('forgotPassword/', forgot_password, name='forgot_password'),
    path('logout/', logout, name='logout'),

    path('register/', register, name='register'),
    path('usersList/', users_list, name='users_list'),
    path('userDelete/<int:id>', users_delete, name='users_delete'),

    path('rolesList/', roles_list, name='roles_list'),
    path('rolesAdd/', roles_process, name='roles_add'),
    path('rolesEdit/<int:id>', roles_process, name='roles_edit'),
    path('rolesDelete/<int:id>', roles_delete, name='roles_delete'),

    path('customerList/', customer_list, name='customer_list'),
    path('customerAdd/', customer_process, name='customer_add'),
    path('customerEdit/<int:id>', customer_process, name='customer_edit'),
    path('customerDelete/<int:id>', customer_delete, name='customer_delete'),

    path('supplierList/', supplier_list, name='supplier_list'),
    path('supplierAdd/', supplier_process, name='supplier_add'),
    path('supplierEdit/<int:id>', supplier_process, name='supplier_edit'),
    path('supplierDelete/<int:id>', supplier_delete, name='supplier_delete'),

    path('menusList/', menus_list, name='menus_list'),
    path('menusAdd/', menus_process, name='menus_add'),
    path('menusEdit/<int:id>', menus_process, name='menus_edit'),
    path('menusDelete/<int:id>', menus_delete, name='menus_delete'),

    path('modulesList/', modules_list, name='modules_list'),
    path('modulesAdd/', modules_process, name='modules_add'),
    path('modulesEdit/<int:id>', modules_process, name='modules_edit'),
    path('modulesDelete/<int:id>', modules_delete, name='modules_delete'),

    path('urlsList/', urls_list, name='urls_list'),
    path('urlsAdd/', urls_process, name='urls_add'),
    path('urlsEdit/<int:id>', urls_process, name='urls_edit'),
    path('urlsDelete/<int:id>', urls_delete, name='urls_delete'),

    path('privilege/<int:id>', privilege_list, name='privilege_list'),
    # path('groupPrivilege/<int:id>', group_privilege_list, name='group_privilege_list'),

]

configuration/urls.py
from django.urls import path
from .views import *

app_name = 'configuration'

urlpatterns = [
    # Category
    path('category/', CategoryListView.as_view(), name='CategoryListView'),
    path('category/add/', CategoryCreateView.as_view(), name='CategoryCreateView'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='CategoryUpdateView'),
    path('category/delete/<int:id>/', CategoryDeleteView, name='CategoryDeleteView'),

    # Discount
    path('discount/', DiscountListView.as_view(), name='DiscountListView'),
    path('discount/add/', DiscountCreateView.as_view(), name='DiscountCreateView'),
    path('discount/edit/<int:pk>/', DiscountUpdateView.as_view(), name='DiscountUpdateView'),
    path('discount/delete/<int:id>/', DiscountDeleteView, name='DiscountDeleteView'),
]

items/urls.py
from django.urls import path
from .views import *

app_name = 'items'

urlpatterns = [
    # Product
    path('product/', ProductListView.as_view(), name='ProductListView'),
    path('product/add/', ProductCreateView.as_view(), name='ProductCreateView'),
    path('product/details/<int:id>/', ProductDetailsView, name='ProductDetailsView'),
    path('product/edit/<int:id>/', ProductUpdateView, name='ProductUpdateView'),
    path('product/delete/<int:id>/', ProductDeleteView, name='ProductDeleteView'),

    # Stock
    path('stock/', StockListView.as_view(), name='StockListView'),
    path('stock/add/', StockCreateView.as_view(), name='StockCreateView'),
    # path('stock/edit/<int:id>/', StockUpdateView, name='StockUpdateView'),
    # path('stock/delete/<int:id>/', StockDeleteView, name='StockDeleteView'),

    # Order
    path('order/', OrderListView.as_view(), name='OrderListView'),
    path('order/create/<int:id>/', OrderCreate, name='OrderCreate'),
    path('order/add/', OrderCreateView, name='OrderCreateView'),
    # path('order/edit/<int:pk>/', OrderUpdateView.as_view(), name='OrderUpdateView'),
    # path('order/delete/<int:id>/', OrderDeleteView, name='OrderDeleteView'),

    path('check_img/<product_id>/', check_img, name='check_img'),

]

report/urls.py
from django.urls import path
from .views import *

app_name = 'report'

urlpatterns = [
    path('customer_report', customer_report, name='customer_report'),
    path('export_customer_report', export_customer_report, name='export_customer_report'),

    path('supplier_report', supplier_report, name='supplier_report'),
    path('export_supplier_report', export_supplier_report, name='export_supplier_report'),

    path('product_report', product_report, name='product_report'),
    path('export_product_report', export_product_report, name='export_product_report'),

    path('stock_report', stock_report, name='stock_report'),
    path('export_stock_report', export_stock_report, name='export_stock_report'),

    path('sales_report', sales_report, name='sales_report'),
    path('export_sales_report', export_sales_report, name='export_sales_report'),

    path('profit_loss_report', profit_loss_report, name='profit_loss_report'),
    path('export_profit_loss_report', export_profit_loss_report, name='export_profit_loss_report'),
]

ssms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('configuration/', include('configuration.urls')),
    path('items/', include('items.urls')),
    path('report/', include('report.urls')),
]

templates/includes/base.html
{% load static %}
{% include 'includes/header.html' %}
{% include 'includes/footer.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}SSMS{% endblock %}</title>
</head>
<body>

<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left">
                    <li><h1 class="logo-wrapper"><img
                            src="{% static '' %}images/ssms.png" alt="ssms"
                            style="position: fixed; top: -4px; left: 130px; width: 15%; height: 9%;"> <span
                            class="logo-text">SSMS</span>
                    </h1></li>
                </ul>
                <form action="{% url 'account:index' %}" method="post" enctype="multipart/form-data" id="myForm">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col s12 m8 l8">

                            <div class="header-search-wrapper hide-on-med-and-down right">
                                <i class="mdi-action-search"></i>
                                <input style="width: 80%" type="text" name="Search" value="{{ search_text }}"
                                       class="header-search-input z-depth-2"
                                       placeholder="Search"/>
                            </div>

                        </div>

                        <div class="col s12 m4 l4">

                            <ul class="right hide-on-med-and-down">
                                <li>
                                    <p>
                                        <button name="search_btn" id="search_btn"
                                                class="btn-floating btn-large waves-effect waves-light blue-grey"
                                                type="submit"
                                                style="position: absolute; margin-top: -10px; margin-left: -100px">
                                            <i class="mdi-action-search"></i></button>
                                    </p>
                                </li>
                                <li><a href="#" data-activates="chat-out"
                                       class="waves-effect waves-block waves-light chat-collapse"></a>
                                </li>
                                {#                        <li><a href="javascript:void(0);"#}
                                {#                               class="waves-effect waves-block waves-light translation-button"#}
                                {#                               data-activates="translation-dropdown">ENGLISH</a>#}
                                {#                        </li>#}
                                <li><a onclick="Eng_Clicked()"
                                       class="waves-effect waves-block waves-light translation-button"
                                       data-activates="translation-dropdown"><img src="{% static '' %}images/UK.png"
                                                                                  alt="UK"/></a>
                                </li>
                                <li><a onclick="Ban_Clicked()"
                                       class="waves-effect waves-block waves-light translation-button"
                                       data-activates="translation-dropdown"><img src="{% static '' %}images/BD.png"
                                                                                  alt="BD"/></a></li>
                                <li><a href="javascript:void(0);"
                                       class="waves-effect waves-block waves-light toggle-fullscreen"><i
                                        class="mdi-action-settings-overscan"></i></a>
                                </li>
                                <li>
                                    <a href="{% url 'account:logout' %}">
                                        {% if data.language == "Eng" %}
                                            Logout
                                        {% else %}
                                            প্রস্থান
                                        {% endif %}
                                    </a>
                                </li>
                            </ul>

                        </div>

                    </div>
                    <input type="hidden" id="language" name="language" value="">
                </form>
            </div>
        </nav>
    </div>
</header>

<!-- Start Page Loading -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<div id="main" style="min-height: 82vh">
    <!-- START WRAPPER -->
    <div class="wrapper">

        <!-- START LEFT SIDEBAR NAV-->
        <aside id="left-sidebar-nav">
            <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class="bold active"><a href="{% url 'account:index' %}" class="waves-effect waves-cyan"><i
                        class="mdi-action-dashboard"></i> Dashboard</a>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i
                                class="mdi-action-account-box"></i> Accounts</a>
                            <div class="collapsible-body">
                                <ul>
                                    {% for url in request.session.urls %}
                                        {% if url == 'users_list' %}
                                            <li><a href="{% url 'account:users_list' %}">Users</a></li>
                                        {% elif url == 'roles_list' %}
                                            <li><a href="{% url 'account:roles_list' %}">Roles</a></li>
                                        {% elif url == 'customer_list' %}
                                            <li><a href="{% url 'account:customer_list' %}">Customers</a></li>
                                        {% elif url == 'supplier_list' %}
                                            <li><a href="{% url 'account:supplier_list' %}">Suppliers</a></li>
                                        {% elif url == 'menus_list' %}
                                            <li><a href="{% url 'account:menus_list' %}">Menus</a></li>
                                        {% elif url == 'modules_list' %}
                                            <li><a href="{% url 'account:modules_list' %}">Modules</a></li>
                                        {% elif url == 'urls_list' %}
                                            <li><a href="{% url 'account:urls_list' %}">URLs</a></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i
                                class="mdi-notification-sync-problem"></i> Configuration</a>
                            <div class="collapsible-body">
                                <ul>
                                    {% for url in request.session.urls %}
                                        {% if url == 'CategoryListView' %}
                                            <li><a href="{% url 'configuration:CategoryListView' %}">Category</a></li>
                                        {% elif url == 'DiscountListView' %}
                                            <li><a href="{% url 'configuration:DiscountListView' %}">Discount</a></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i
                                class="mdi-action-shopping-cart"></i> Items</a>
                            <div class="collapsible-body">
                                <ul>
                                    {% for url in request.session.urls %}
                                        {% if url == 'ProductListView' %}
                                            <li><a href="{% url 'items:ProductListView' %}">Product</a></li>
                                        {% elif url == 'StockListView' %}
                                            <li><a href="{% url 'items:StockListView' %}">Stock</a></li>
                                        {% elif url == 'OrderListView' %}
                                            <li><a href="{% url 'items:OrderListView' %}">Order</a></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i
                                class="mdi-action-assignment"></i> Report</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="{% url 'report:customer_report' %}">Customer</a></li>
                                    <li><a href="{% url 'report:supplier_report' %}">Supplier</a></li>
                                    <li><a href="{% url 'report:product_report' %}">Product</a></li>
                                    <li><a href="{% url 'report:stock_report' %}">Stock</a></li>
                                    <li><a href="{% url 'report:sales_report' %}">Sales</a></li>
                                    <li><a href="{% url 'report:profit_loss_report' %}">Profit/Loss</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </aside>
        <section id="content">
            <div class="container">
                <br>
                <br>
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </div>
</div>

<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            Copyright © 2020 <a class="grey-text text-lighten-4"
                                href="http://themeforest.net/user/geekslabs/portfolio?ref=geekslabs"
                                target="_blank">Jahangirnagar University. </a> All rights reserved.
            <span class="right"> Developed by <a class="grey-text text-lighten-4"
                                                 href="http://geekslabs.com/">Asif Ahmed</a></span>
        </div>
    </div>
</footer>

<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #00bcd4;
    }

    li {
        float: left;
    }

    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li a:hover:not(.active) {
        background-color: #070707;
    }
</style>

<script>
    function Eng_Clicked() {
        document.getElementById("language").value = "Eng";
        document.getElementById("myForm").submit();
    }

    function Ban_Clicked() {
        document.getElementById("language").value = "Ban";
        document.getElementById("myForm").submit();
    }
</script>

</body>

</html>

templates/includes/footer.html
{% load static %}

<body>
<!-- jQuery Library -->
{#<script src="{% static '' %}js/others/tinymce.min.js"></script>#}
<script type="text/javascript" src="{% static '' %}js/plugins/jquery-1.11.2.min.js"></script>
{#<script src="{% static '' %}js/others/jquery.tinymce.min.js"></script>#}

<script src="{% static '' %}js/datepick/jquery-ui.js"></script>

<!--materialize js-->
<script type="text/javascript" src="{% static '' %}js/materialize.min.js"></script>

<!--prism-->
<script type="text/javascript" src="{% static '' %}js/plugins/prism/prism.js"></script>

<!--scrollbar-->
<script type="text/javascript" src="{% static '' %}js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

<!-- data-tables -->
<script type="text/javascript" src="{% static '' %}js/plugins/data-tables/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{% static '' %}js/plugins/data-tables/data-tables-script.js"></script>
{#<script src = "{% static '' %}js/plugins/data-tables/jquery.dataTables.min.js" defer ></script>#}

{#<!-- chartist -->#}
{#<script type="text/javascript" src="{% static '' %}js/plugins/chartist-js/chartist.min.js"></script>#}

<!-- sparkline -->
<script type="text/javascript" src="{% static '' %}js/plugins/sparkline/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="{% static '' %}js/plugins/sparkline/sparkline-script.js"></script>

<!--jvectormap-->
<script type="text/javascript" src="{% static '' %}js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script type="text/javascript" src="{% static '' %}js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script type="text/javascript" src="{% static '' %}js/plugins/jvectormap/vectormap-script.js"></script>

<!--plugins.js - Some Specific JS codes for Plugin Settings-->
<script type="text/javascript" src="{% static '' %}js/plugins.min.js"></script>
<!--custom-script.js - Add your own theme custom JS-->
<script type="text/javascript" src="{% static '' %}js/custom-script.js"></script>

<!-- Toast Notification -->
</body>

{#<!-- jQuery -->#}
{#<script src="{% static '' %}js/jquery-3.3.1.slim.min.js"#}
{#        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#        crossorigin="anonymous"></script>#}

{#<!-- XDSoft DateTimePicker -->#}
{#<script src="{% static '' %}js/jquery.datetimepicker.full.min.js"#}
{#        integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>#}

<!-- SweetAlert Plugin Js -->
<script src="{% static '' %}js/plugins/sweetalert/sweetalert.min.js"></script>

</html>

templates/includes/header.html
{% load static %}

<!doctype html>

<html class=no-js lang=en>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>🆂🆂🅼🆂</title>

    <!-- Favicons-->
    {#    <link rel="icon" href="{% static '' %}images/favicon/favicon-32x32.png" sizes="32x32">#}
    <link rel="icon" href="{% static '' %}images/ssms.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="{% static '' %}images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="{% static '' %}images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->

    <link rel="stylesheet" href="{% static '' %}css/datepick/jquery-ui.css">

    <!-- CORE CSS-->
    <link href="{% static '' %}css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <!-- Custome CSS-->
    <link href="{% static '' %}css/custom/custom.min.css" type="text/css" rel="stylesheet" media="screen,projection">

    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="{% static '' %}js/plugins/prism/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="{% static '' %}js/plugins/data-tables/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="{% static '' %}js/plugins/jvectormap/jquery-jvectormap.css" type="text/css" rel="stylesheet"
          media="screen,projection">
{#    <link rel="stylesheet" href="{% static '' %}css/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />#}

    <link rel="stylesheet" href="{% static '' %}js/plugins/sweetalert/sweetalert.css">

</head>

templates/includes/login_style.html
{% load static %}

<!doctype html>

<html class=no-js lang=en>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>🆂🆂🅼🆂</title>

    <!-- Favicons-->
    {#    <link rel="icon" href="{% static '' %}images/favicon/favicon-32x32.png" sizes="32x32">#}
    <link rel="icon" href="{% static '' %}images/ssms.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="{% static '' %}images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="{% static '' %}images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->

    <!-- CORE CSS-->
    <link href="{% static '' %}css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <!-- Custome CSS-->
    <link href="{% static '' %}css/custom/custom.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}css/layouts/page-center.css" type="text/css" rel="stylesheet" media="screen,projection">
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="{% static '' %}js/plugins/prism/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static '' %}js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
</head>

<body class="cyan">
<!-- Start Page Loading -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

    {% block content %}
    {% endblock %}

<!-- jQuery Library -->
<script src="{% static '' %}js/others/tinymce.min.js"></script>
<script type="text/javascript" src="{% static '' %}js/plugins/jquery-1.11.2.min.js"></script>
<script src="{% static '' %}js/others/jquery.tinymce.min.js"></script>

<!--materialize js-->
<script type="text/javascript" src="{% static '' %}js/materialize.min.js"></script>

<!--prism-->
<script type="text/javascript" src="{% static '' %}js/plugins/prism/prism.js"></script>

<!--scrollbar-->
<script type="text/javascript" src="{% static '' %}js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

<!--plugins.js - Some Specific JS codes for Plugin Settings-->
<script type="text/javascript" src="{% static '' %}js/plugins.min.js"></script>
<!--custom-script.js - Add your own theme custom JS-->
<script type="text/javascript" src="{% static '' %}js/custom-script.js"></script>

</body>

</html>