account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', login, name='login'),
    path('signup/', login, name='login'),
    path('jk34BB23BHddv12HsNNJ/', login_validate, name='login_validate'),
    path('index/', index, name='index'),

    # path('forgotPassword/', forgot_password, name='forgot_password'),
    path('logout/', logout, name='logout'),

    path('register/', register, name='register'),
    path('usersList/', users_list, name='users_list'),
    path('userDelete/<int:id>', users_delete, name='users_delete'),

    path('rolesList/', roles_list, name='roles_list'),
    path('rolesAdd/', roles_process, name='roles_add'),
    path('rolesEdit/<int:id>', roles_process, name='roles_edit'),
    path('rolesDelete/<int:id>', roles_delete, name='roles_delete'),

    path('customerList/', customer_list, name='customer_list'),
    path('customerAdd/', customer_process, name='customer_add'),
    path('customerEdit/<int:id>', customer_process, name='customer_edit'),
    path('customerDelete/<int:id>', customer_delete, name='customer_delete'),

    path('supplierList/', supplier_list, name='supplier_list'),
    path('supplierAdd/', supplier_process, name='supplier_add'),
    path('supplierEdit/<int:id>', supplier_process, name='supplier_edit'),
    path('supplierDelete/<int:id>', supplier_delete, name='supplier_delete'),

    path('menusList/', menus_list, name='menus_list'),
    path('menusAdd/', menus_process, name='menus_add'),
    path('menusEdit/<int:id>', menus_process, name='menus_edit'),
    path('menusDelete/<int:id>', menus_delete, name='menus_delete'),

    path('modulesList/', modules_list, name='modules_list'),
    path('modulesAdd/', modules_process, name='modules_add'),
    path('modulesEdit/<int:id>', modules_process, name='modules_edit'),
    path('modulesDelete/<int:id>', modules_delete, name='modules_delete'),

    path('urlsList/', urls_list, name='urls_list'),
    path('urlsAdd/', urls_process, name='urls_add'),
    path('urlsEdit/<int:id>', urls_process, name='urls_edit'),
    path('urlsDelete/<int:id>', urls_delete, name='urls_delete'),

    path('privilege/<int:id>', privilege_list, name='privilege_list'),
    # path('groupPrivilege/<int:id>', group_privilege_list, name='group_privilege_list'),

]

items/urls.py
from django.urls import path
from .views import *

app_name = 'items'

urlpatterns = [
    # Product
    path('product/', ProductListView.as_view(), name='ProductListView'),
    path('product/add/', ProductCreateView.as_view(), name='ProductCreateView'),
    path('product/details/<int:id>/', ProductDetailsView, name='ProductDetailsView'),
    path('product/edit/<int:id>/', ProductUpdateView, name='ProductUpdateView'),
    path('product/delete/<int:id>/', ProductDeleteView, name='ProductDeleteView'),

    # Stock
    path('stock/', StockListView.as_view(), name='StockListView'),
    path('stock/add/', StockCreateView.as_view(), name='StockCreateView'),
    # path('stock/edit/<int:id>/', StockUpdateView, name='StockUpdateView'),
    # path('stock/delete/<int:id>/', StockDeleteView, name='StockDeleteView'),

    # Order
    path('order/', OrderListView.as_view(), name='OrderListView'),
    path('order/create/<int:id>/', OrderCreate, name='OrderCreate'),
    path('order/add/', OrderCreateView, name='OrderCreateView'),
    # path('order/edit/<int:pk>/', OrderUpdateView.as_view(), name='OrderUpdateView'),
    # path('order/delete/<int:id>/', OrderDeleteView, name='OrderDeleteView'),

    path('check_img/<product_id>/', check_img, name='check_img'),

]

ssms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('configuration/', include('configuration.urls')),
    path('items/', include('items.urls')),
    path('report/', include('report.urls')),
]

items/models.py
from django.db import models
from configuration.models import *
from account.models import Customer, Supplier


SIZE_CHOICES = (
    ("Small", 'Small'),
    ("Medium", 'Medium'),
    ("Large", 'Large'),
)


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.CharField(max_length=20, blank=True, null=True)
    size = models.CharField(choices=SIZE_CHOICES, max_length=6)
    price = models.FloatField()
    quantity_left = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    image = models.FileField(null=True, blank=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_by = models.IntegerField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + " (" + self.size + ")"

    class Meta:
        db_table = 'I_PRODUCT'


class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    expiry_date = models.DateTimeField(blank=True, null=True)
    buying_price = models.FloatField()
    quantity = models.IntegerField()
    total_price = models.FloatField(default=0.0)
    description = models.TextField(blank=True, null=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_by = models.IntegerField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    def get_total(self):
        total = self.buying_price * self.quantity
        return total

    class Meta:
        db_table = 'I_STOCK'


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField()
    net_total = models.FloatField(default=0.0)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    ordered_date = models.DateField()
    shipping_address = models.CharField(max_length=100, blank=True, null=True)
    billing_address = models.CharField(max_length=100, blank=True, null=True)
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, blank=True, null=True)
    # is_tax_payable = models.BooleanField(default=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_by = models.IntegerField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    def get_total(self):
        total = self.product.price * self.quantity
        if self.discount:
            total -= (total * (self.discount.rate/100))
        # if self.is_tax_payable == True:
        #     total += (total * (15/100))
        return total

    class Meta:
        db_table = 'I_ORDER'

items/views.py
from .forms import *
from django.urls import reverse_lazy
from account.decorators import *
from django.views.generic import ListView, CreateView, UpdateView
from datetime import datetime
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import socket
from .tasks import send_task_mail


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class ProductListView(ListView):
    model = Product
    template_name = 'items/product_list.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'items/product_form.html'
    success_url = reverse_lazy('items:ProductListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            if Product.objects.filter(name=self.request.POST['name'],
                                      brand=self.request.POST['brand'],
                                      size=self.request.POST['size']).exists():
                messages.error(self.request, 'Product Already Exists.')
                return super(ProductListView, self).form_invalid(form)
            item.image = self.request.POST['b64']
            item.created_date = datetime.today()
            item.created_by = self.request.session['id']
            item.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(ProductCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(ProductCreateView, self).form_invalid(form)


def ProductDetailsView(request, id):
    try:
        userdata = {
            'user_id': request.session['id'],
            'username': request.session['username'],
            'language': request.session['language'],
            'urls': request.session['urls'],
        }
        item_obj = get_object_or_404(Product, pk=id)
        try:
            stock_obj = Stock.objects.filter(product_id=id).latest('id')
        except:
            stock_obj = None
        form = ProductForm(request.POST or None, instance=item_obj)
        context = dict()
        context['data'] = userdata
        img_text = item_obj.image
        context['src_image'] = img_text.decode('utf-8')
        context['item'] = item_obj
        context['stock_item'] = stock_obj
        if request.method == 'POST' and id:
            if form.is_valid():
                item = form.save(commit=False)
                item.updated_by = request.session['id']
                item.updated_date = datetime.now()
                if request.POST['b64'] != "":
                    item.image = request.POST['b64']
                else:
                    item.image = img_text.decode('utf-8')
                item.save()
                messages.success(request, 'Data Successfully Updated')
                return redirect('items:ProductListView')
        return render(request, 'items/product_details.html', context)
    except Exception as ex:
        messages.error(request, str(ex))
        return redirect('items:ProductListView')


@login_required("logged_in", 'account:login')
@access_permission_required
def ProductUpdateView(request, id):
    try:
        userdata = {
            'user_id': request.session['id'],
            'username': request.session['username'],
            'language': request.session['language'],
            'urls': request.session['urls'],
        }
        item_obj = get_object_or_404(Product, pk=id)
        form = ProductForm(request.POST or None, instance=item_obj)
        context = dict()
        context['data'] = userdata
        context['form'] = form
        img_text = item_obj.image
        context['src_image'] = img_text.decode('utf-8')

        if request.method == 'POST' and id:
            if form.is_valid():
                item = form.save(commit=False)
                if Product.objects.filter(name=request.POST['name'],
                                          brand=request.POST['brand'],
                                          size=request.POST['size']).exclude(id=id).exists():
                    messages.error(request, 'Product Already Exists.')
                    return redirect('items:ProductListView')
                item.updated_by = request.session['id']
                item.updated_date = datetime.now()
                if request.POST['b64'] != "":
                    item.image = request.POST['b64']
                else:
                    item.image = img_text.decode('utf-8')
                item.save()
                messages.success(request, 'Data Successfully Updated')
                return redirect('items:ProductListView')
        return render(request, 'items/product_form.html', context)
    except Exception as ex:
        messages.error(request, str(ex))
        return redirect('items:ProductListView')


@login_required("logged_in", 'account:login')
@access_permission_required
def ProductDeleteView(request, id):
    Product.objects.get(pk=id).delete()
    messages.error(request, 'Data Successfully Deleted')
    return redirect('items:ProductListView')


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class StockListView(ListView):
    model = Stock
    template_name = 'items/stock_list.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(StockListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class StockCreateView(CreateView):
    model = Stock
    form_class = StockForm
    template_name = 'items/stock_form.html'
    success_url = reverse_lazy('items:StockListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(StockCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            item.total_price = item.get_total()
            item.created_date = datetime.today()
            item.created_by = self.request.session['id']
            product_obj = Product.objects.get(id=self.request.POST['product'])
            Product.objects.filter(id=self.request.POST['product']).update(quantity_left=int(product_obj.quantity_left) + int(self.request.POST['quantity']))
            item.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(StockCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(StockCreateView, self).form_invalid(form)


# @login_required("logged_in", 'account:login')
# @access_permission_required
# def StockUpdateView(request, id):
#     try:
#         userdata = {
#             'user_id': request.session['id'],
#             'username': request.session['username'],
#             'urls': request.session['urls'],
#         }
#         item_obj = get_object_or_404(Stock, pk=id)
#         form = StockForm(request.POST or None, instance=item_obj)
#         context = dict()
#         context['data'] = userdata
#         context['form'] = form
#         if request.method == 'POST' and id:
#             if form.is_valid():
#                 item = form.save(commit=False)
#                 item.total_price = item.get_total()
#                 item.updated_by = request.session['id']
#                 item.updated_date = datetime.now()
#                 item.save()
#                 messages.success(request, 'Data Successfully Updated')
#                 return redirect('items:StockListView')
#         return render(request, 'items/stock_form.html', context)
#     except Exception as ex:
#         messages.error(request, str(ex))
#         return redirect('items:StockListView')


# @login_required("logged_in", 'account:login')
# @access_permission_required
# def StockDeleteView(request, id):
#     Stock.objects.get(pk=id).delete()

templates/items/order_form.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2">
                                {% if data.language == "Eng" %}
                                    Order Form
                                {% else %}
                                    অর্ডার ফর্ম
                                {% endif %}
                            </h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="" class="col s12" method="post" enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="input-field col s12" id="img_div">
                                        <br>
                                        <br>
                                        <img id="img" src="{{ src_image }}" height="100">
                                        <br>
                                        <br>
                                    </div>
                                    <div class="row">
                                        {% for field in form %}
                                            <div class="input-field col s12">
                                                {{ field }}
                                                <label for="{{ field.id_for_label }}">{{ field.label }} <span
                                                        class="text-danger">*</span></label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <a href="{% url 'items:OrderListView' %}"
                                                   class="btn waves-effect waves-light brown"><i
                                                        class="mdi-content-clear left"></i>
                                                    {% if data.language == "Eng" %}
                                                        Cancel
                                                    {% else %}
                                                        বাতিল করুন
                                                    {% endif %}
                                                </a>
                                                <button class="btn cyan waves-effect waves-light right" type="submit"
                                                        name="action">
                                                    {% if data.language == "Eng" %}
                                                        Submit
                                                    {% else %}
                                                        দাখিল করুন
                                                    {% endif %}
                                                    <i class="mdi-content-send right"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(document).ready(function () {
            $('#img_div').hide();
            if (document.getElementById("img").src != "") {
                $('#img_div').show();
            }
        });

        $('#id_product').on('change', function () {
            var product_id = $('#id_product').val();
            if (product_id != "") {
                $.ajax({
                    url: '/items/check_img/' + product_id + '/',
                    type: 'post',
                    data: {depart: product_id},
                    dataType: 'json',
                    success: function (response) {
                        document.getElementById("img").src = response['code'];
                        $('#img_div').show();
                    }
                });
            }
            else {
                $('#img_div').hide();
            }
        });

        $(function () {
            $("#datepicker").datepicker();
        });
    </script>

{% endblock %}

templates/items/product_list.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="table-datatables">
                <div class="row">
                    <div>
                        <h4 class="header">
                            {% if data.language == "Eng" %}
                                Product List
                            {% else %}
                                পণ্য লিস্ট
                            {% endif %}
                        </h4>
                    </div>
                    <div style="float: right">
                        <a href="{% url 'items:ProductCreateView' %}"
                           class="btn waves-effect waves-light light-green darken-4"><i
                                class="mdi-content-add left"></i>
                            {% if data.language == "Eng" %}
                                Add Product
                            {% else %}
                                পণ্য ফর্ম
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="divider"></div>
                <div class="row">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S/L</th>
                            <th>Name</th>
                            <th>Brand</th>
                            <th>Category</th>
                            <th>Size</th>
                            <th>Quantity Left</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for each in items %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ each.name }}</td>
                                <td>{{ each.brand }}</td>
                                <td>{{ each.category.name }}</td>
                                <td>{{ each.size }}</td>
                                <td>{{ each.quantity_left }}</td>
                                <td>{{ each.price }}</td>
                                <td>
                                    <a href="{% url 'items:ProductDetailsView' each.id %}"
                                       class="btn-floating waves-effect waves-light indigo"><i
                                            class="mdi-action-view-list"></i></a>
                                    <a href="{% url 'items:ProductUpdateView' each.id %}"
                                       class="btn-floating waves-effect waves-light deep-orange"><i
                                            class="mdi-editor-mode-edit"></i></a>
                                    <a href="#" id="del_btn" name="{{ each.id }}"
                                       class="btn-floating waves-effect waves-light red"><i
                                            class="mdi-action-delete"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).on('click', '#del_btn', function (event) {
            var url = "{% url 'items:ProductDeleteView' 123 %}";
            var id = $(this).attr('name');
            event.preventDefault();
            confirmMessage(url, id);
        });

        function confirmMessage(url, id) {
            swal({
                    title: "Delete Request",
                    text: "Are you sure want to delete ?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes",
                    cancelButtonText: "No",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function (isConfirm) {
                    if (!(isConfirm)) {
                        swal("Operation Cancelled", "...");
                    } else {
                        document.location.href = url.replace('123', id);
                    }
                });
        }
    </script>

{% endblock %}