report/urls.py
from django.urls import path
from .views import *

app_name = 'report'

urlpatterns = [
    path('customer_report', customer_report, name='customer_report'),
    path('export_customer_report', export_customer_report, name='export_customer_report'),

    path('supplier_report', supplier_report, name='supplier_report'),
    path('export_supplier_report', export_supplier_report, name='export_supplier_report'),

    path('product_report', product_report, name='product_report'),
    path('export_product_report', export_product_report, name='export_product_report'),

    path('stock_report', stock_report, name='stock_report'),
    path('export_stock_report', export_stock_report, name='export_stock_report'),

    path('sales_report', sales_report, name='sales_report'),
    path('export_sales_report', export_sales_report, name='export_sales_report'),

    path('profit_loss_report', profit_loss_report, name='profit_loss_report'),
    path('export_profit_loss_report', export_profit_loss_report, name='export_profit_loss_report'),
]

ssms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('configuration/', include('configuration.urls')),
    path('items/', include('items.urls')),
    path('report/', include('report.urls')),
]

report/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from account.models import Customer, Supplier
from items.models import Product, Stock, Order
from account.decorators import login_required
from datetime import datetime, date, time
from django.http import HttpResponse
from django.db.models import Sum
from django.core.files.storage import FileSystemStorage
from reportlab.lib.enums import TA_CENTER
import reportlab.lib.pagesizes
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter, landscape
import xlwt
import calendar
import ssms.settings
import logging.config
log = ssms.settings.log_setting()
logging.config.dictConfig(log)
mylog = logging.getLogger('report')


def myFirstPage(canvas, doc):
    canvas.saveState()
    canvas.setFont('Times-Roman', 9)
    canvas.drawString(inch, 0.75 * inch, "Page %d" % (doc.page))
    canvas.restoreState()


def myLaterPages(canvas, doc):
    canvas.saveState()
    canvas.setFont('Times-Roman', 9)
    canvas.drawString(inch, 0.75 * inch, "Page %d" % (doc.page))
    canvas.restoreState()


def myLandscapePage(canvas, doc):
    canvas.saveState()
    canvas.setPageSize(landscape(letter))
    canvas.setFont('Times-Roman', 9)
    canvas.drawString(inch, 0.75 * inch, "Page %d %s" % (doc.page, ""))
    canvas.restoreState()


"""Customer Report"""
@login_required("logged_in", 'account:login')
def customer_report(request):
    try:
        language = "Eng"
        if 'language' in request.session:
            language = request.session['language']
        userdata = {
            'user_id': request.session['id'],
            'username': request.session['username'],
            'urls': request.session['urls'],
            'language': language,
        }
        context = {
            'data': userdata,
        }
        return render(request, 'report/customer_report.html', context)
    except Exception as ex:
        messages.error(request, str(ex))
        return redirect('account:index')


@login_required("logged_in", 'account:login')
def export_customer_report(request):
    try:
        if request.method == 'POST':
            dataset = Customer.objects.all()
            if not dataset.exists():
                messages.error(request, 'No Data Found')
                return redirect('report:customer_report')

            if 'xls_export' in request.POST:
                response = HttpResponse(content_type='application/ms-excel')
                response['Content-Disposition'] = 'attachment; filename="Customer Report.xls"'
                wb = xlwt.Workbook(encoding='utf-8', style_compression=2)
                ws = wb.add_sheet('customer_report')
                row_num = 3

                font_style = xlwt.XFStyle()
                common = "font:name Calibri, bold on, height 200;  align:wrap yes, horiz center, vert center ;"
                common1 = "align: wrap yes, horiz right, vert center ;"

                columns = ['SL', 'Name', 'E-mail', 'Phone', 'Address']

                ws.write_merge(0, 1, 0, 5, 'Customer Report', xlwt.easyxf(common))
                for col in range(len(columns)):
                    ws.write(row_num, col, columns[col], font_style)
                row_num += 1
                for count, data in enumerate((dataset)):
                    ws.write(row_num, 0, count + 1, font_style)
                    ws.write(row_num, 1, data.name, font_style)
                    ws.write(row_num, 2, data.email, font_style)
                    ws.write(row_num, 3, data.phone, font_style)
                    ws.write(row_num, 4, data.address, xlwt.easyxf(common1))
                    row_num += 1

                wb.save(response)
                return response

            elif 'pdf_export' in request.POST:
                styles = getSampleStyleSheet()
                doc = SimpleDocTemplate("assets/pdf_files/Customer Report.pdf", pagesize=reportlab.lib.pagesizes.letter)
                parastyles = ParagraphStyle(
                    'header',
                    parent=styles['Normal'],
                    fontName='Helvetica-Bold',
                    fontSize=8,
                    alignment=TA_CENTER,
                    textColor=colors.black,
                )
                story = []
                elements = []
                columns = []
                columns.insert(0, [Paragraph('S/L', parastyles),
                                   Paragraph('Name', parastyles),
                                   Paragraph('Email', parastyles),
                                   Paragraph('Phone', parastyles),
                                   Paragraph('Address', parastyles)])

                texstyles = ParagraphStyle(
                    'text',
                    parent=styles['Normal'],
                    fontSize=8,
                    alignment=TA_CENTER,
                    textColor=colors.black,
                )
                j = 1

                for count, data in enumerate((dataset)):
                    columns.insert(j, [Paragraph(str(j), texstyles),
                                       Paragraph(str(data.name), texstyles),
                                       Paragraph(str(data.email), texstyles),
                                       Paragraph(str(data.phone), texstyles),
                                       Paragraph(str(data.address), texstyles)])
                    j = j + 1

                t = Table(columns, repeatRows=1, splitByRow=1)
                t.setStyle(TableStyle(
                    [
                        ('FONTSIZE', (0, 0), (-1, -1), 1),
                        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.gray),
                        ('BOX', (0, 0), (-1, -1), 0.25, colors.black),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP')
                    ]))

                dateofpdf = (datetime.now()).strftime("%d/%m/%Y")
                story.append(Paragraph("Customer Report", parastyles))
                story.append(Spacer(1, 0.2 * inch))
                story.append(Paragraph("Printed Date: " + dateofpdf, styles['Normal']))
                story.append(Spacer(1, 0.2 * inch))
                story.append(Spacer(1, 0.2 * inch))
                elements.append(t)
                story.append(t)
                doc.build(story, onFirstPage=myFirstPage, onLaterPages=myLaterPages)
                fs = FileSystemStorage()
                with fs.open("pdf_files/Customer Report.pdf") as pdf:
                    response = HttpResponse(pdf, content_type='application/pdf')
                    filename = "Customer Report.pdf"
                    response['Content-Disposition'] = 'attachment; filename="{}"'.format(filename)
                    return response
                return response
    except Exception as ex:
        messages.error(request, str(ex))
        mylog.exception('export_customer_report', exc_info=True)
        return redirect('report:customer_report')


"""Supplier Report"""
@login_required("logged_in", 'account:login')
def supplier_report(request):
    try:
        language = "Eng"
        if 'language' in request.session:
            language = request.session['language']
        userdata = {
            'user_id': request.session['id'],
            'username': request.session['username'],
            'urls': request.session['urls'],
            'language': language,
        }
        context = {
            'data': userdata,
        }
        return render(request, 'report/supplier_report.html', context)
    except Exception as ex:
        messages.error(request, str(ex))
        return redirect('account:index')


@login_required("logged_in", 'account:login')
def export_supplier_report(request):
    try:
        if request.method == 'POST':
            dataset = Supplier.objects.all()
            if not dataset.exists():
                messages.error(request, 'No Data Found')
                return redirect('report:supplier_report')

            if 'xls_export' in request.POST:
                response = HttpResponse(content_type='application/ms-excel')
                response['Content-Disposition'] = 'attachment; filename="Supplier Report.xls"'
                wb = xlwt.Workbook(encoding='utf-8', style_compression=2)
                ws = wb.add_sheet('supplier_report')
                row_num = 3

                font_style = xlwt.XFStyle()
                common = "font:name Calibri, bold on, height 200;  align:wrap yes, horiz center, vert center ;"
                common1 = "align: wrap yes, horiz right, vert center ;"

                columns = ['SL', 'Name', 'E-mail', 'Phone', 'Address']

                ws.write_merge(0, 1, 0, 5, 'Supplier Report', xlwt.easyxf(common))
                for col in range(len(columns)):
                    ws.write(row_num, col, columns[col], font_style)
                row_num += 1
                for count, data in enumerate((dataset)):
                    ws.write(row_num, 0, count + 1, font_style)
                    ws.write(row_num, 1, data.name, font_style)
                    ws.write(row_num, 2, data.email, font_style)
                    ws.write(row_num, 3, data.phone, font_style)
                    ws.write(row_num, 4, data.address, xlwt.easyxf(common1))
                    row_num += 1

                wb.save(response)
                return response

            elif 'pdf_export' in request.POST:
                styles = getSampleStyleSheet()
                doc = SimpleDocTemplate("assets/pdf_files/Supplier Report.pdf", pagesize=reportlab.lib.pagesizes.letter)
                parastyles = ParagraphStyle(
                    'header',
                    parent=styles['Normal'],
                    fontName='Helvetica-Bold',
                    fontSize=8,

templates/report/customer_report.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2" style="text-align: center; vertical-align: middle;"><b>
                                {% if data.language == "Eng" %}
                                    Customer Report
                                {% else %}
                                    কাস্টমার রিপোর্ট
                                {% endif %}
                            </b></h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="{% url 'report:export_customer_report' %}" class="col s12" method="post"
                                      enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <button type="submit" name="pdf_export"
                                                        class="btn teal waves-effect waves-light left">
                                                    {% if data.language == "Eng" %}
                                                        Export (.pdf)
                                                    {% else %}
                                                        পি ডি এফ
                                                    {% endif %}
                                                    <i class="mdi-file-file-download left"></i></button>
                                                <button type="submit" name="xls_export"
                                                        class="btn lime darken-3 waves-effect waves-light right">
                                                    {% if data.language == "Eng" %}
                                                        Export (.xls)
                                                    {% else %}
                                                        এক্স এল
                                                    {% endif %}
                                                    <i class="mdi-file-attachment left"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/report/product_report.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2" style="text-align: center; vertical-align: middle;"><b>
                                {% if data.language == "Eng" %}
                                    Product Report
                                {% else %}
                                    পণ্য রিপোর্ট
                                {% endif %}
                            </b></h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="{% url 'report:export_product_report' %}" class="col s12" method="post" enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <button type="submit" name="pdf_export" class="btn teal waves-effect waves-light left">
                                                    {% if data.language == "Eng" %}
                                                        Export (.pdf)
                                                    {% else %}
                                                        পি ডি এফ
                                                    {% endif %}
                                                    <i class="mdi-file-file-download left"></i></button>
                                                <button type="submit" name="xls_export" class="btn lime darken-3 waves-effect waves-light right">
                                                    {% if data.language == "Eng" %}
                                                        Export (.xls)
                                                    {% else %}
                                                        এক্স এল
                                                    {% endif %}
                                                    <i class="mdi-file-attachment left"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/report/profit_loss_report.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2" style="text-align: center; vertical-align: middle; font-size: 140%;"><b>
                                {% if data.language == "Eng" %}
                                    Profit-Loss Report
                                {% else %}
                                    লাভ-ক্ষতির রিপোর্ট
                                {% endif %}
                            </b></h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="{% url 'report:export_profit_loss_report' %}" class="col s12"
                                      method="post" enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="input-field col s12 m6">
                                            <select class="form-control" name="month" id="month" required
                                                    style="font-size: 120%">
                                                <option disabled value="" selected="selected">- - Select Month - -
                                                </option>
                                                <option value="1">January</option>
                                                <option value="2">February</option>
                                                <option value="3">March</option>
                                                <option value="4">April</option>
                                                <option value="5">May</option>
                                                <option value="6">June</option>
                                                <option value="7">July</option>
                                                <option value="8">August</option>
                                                <option value="9">September</option>
                                                <option value="10">October</option>
                                                <option value="11">November</option>
                                                <option value="12">December</option>
                                            </select>
                                        </div>
                                        <div class="input-field col s12 m6">
                                            <div class="form-group">
                                                <input id="year" size="16" style="margin-top: 3px; font-size: 120%;"
                                                       name="year" value="{% now "Y" %}" readonly
                                                       class="date-own filter-status form-control" type="text"
                                                       autocomplete="off">
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <button type="submit" name="pdf_export"
                                                        class="btn teal waves-effect waves-light left">
                                                    {% if data.language == "Eng" %}
                                                        Export (.pdf)
                                                    {% else %}
                                                        পি ডি এফ
                                                    {% endif %}
                                                    <i class="mdi-file-file-download left"></i></button>
                                                <button type="submit" name="xls_export"
                                                        class="btn lime darken-3 waves-effect waves-light right">
                                                    {% if data.language == "Eng" %}
                                                        Export (.xls)
                                                    {% else %}
                                                        এক্স এল
                                                    {% endif %}
                                                    <i class="mdi-file-attachment left"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link href="{% static '' %}css/year_pick/bootstrap.min.css" rel="stylesheet">
    <link href="{% static '' %}css/year_pick/bootstrap-datepicker.css" rel="stylesheet">

    <style>
        #search_btn {
            position: absolute !important;
            margin-top: 2px !important;
            margin-left: -100px !important;
        }

        nav ul a {
            font-size: 1.5rem !important;
        }

        .translation-button img {
            top: 0 !important;
        }

        nav i, nav [class^="mdi-"], nav [class*="mdi-"], nav i.material-icons {
            display: block !important;
            font-size: 2.5rem !important;
        }
    </style>

    <script type="text/javascript" src="{% static '' %}js/plugins/jquery-1.11.2.min.js"></script>
    <script src="{% static '' %}js/year_pick/bootstrap.min.js"></script>
    <script src="{% static '' %}js/year_pick/bootstrap-datepicker.js"></script>

    <script>
        $('.date-own').datepicker({
            minViewMode: 2,
            format: 'yyyy'
        });
    </script>

{% endblock %}

templates/report/sales_report.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2" style="text-align: center; vertical-align: middle;"><b>
                                {% if data.language == "Eng" %}
                                    Sales Report
                                {% else %}
                                    বিক্রী রিপোর্ট
                                {% endif %}
                            </b></h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="{% url 'report:export_sales_report' %}" class="col s12" method="post"
                                      enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="input-field col s12 m6">
                                            <input id="from_date" name="from_date" type='text' class="form-control"
                                                   required>
                                            <label for="from_date">Start Date<span class="text-danger">*</span></label>
                                        </div>
                                        <div class="input-field col s12 m6">
                                            <input id="to_date" name="to_date" type='text' class="form-control"
                                                   required>
                                            <label for="to_date">End Date<span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <button type="submit" name="pdf_export"
                                                        class="btn teal waves-effect waves-light left">
                                                    {% if data.language == "Eng" %}
                                                        Export (.pdf)
                                                    {% else %}
                                                        পি ডি এফ
                                                    {% endif %}
                                                    <i class="mdi-file-file-download left"></i></button>
                                                <button type="submit" name="xls_export"
                                                        class="btn lime darken-3 waves-effect waves-light right">
                                                    {% if data.language == "Eng" %}
                                                        Export (.xls)
                                                    {% else %}
                                                        এক্স এল
                                                    {% endif %}
                                                    <i class="mdi-file-attachment left"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#from_date").datepicker();
            $("#to_date").datepicker();
        });
    </script>

{% endblock %}