configuration/urls.py
from django.urls import path
from .views import *

app_name = 'configuration'

urlpatterns = [
    # Category
    path('category/', CategoryListView.as_view(), name='CategoryListView'),
    path('category/add/', CategoryCreateView.as_view(), name='CategoryCreateView'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='CategoryUpdateView'),
    path('category/delete/<int:id>/', CategoryDeleteView, name='CategoryDeleteView'),

    # Discount
    path('discount/', DiscountListView.as_view(), name='DiscountListView'),
    path('discount/add/', DiscountCreateView.as_view(), name='DiscountCreateView'),
    path('discount/edit/<int:pk>/', DiscountUpdateView.as_view(), name='DiscountUpdateView'),
    path('discount/delete/<int:id>/', DiscountDeleteView, name='DiscountDeleteView'),
]

ssms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('configuration/', include('configuration.urls')),
    path('items/', include('items.urls')),
    path('report/', include('report.urls')),
]

configuration/models.py
from django.db import models
from auditlog.registry import auditlog


class Category(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    created_by = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_by = models.IntegerField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'C_CATEGORY'


class Discount(models.Model):
    name = models.CharField(max_length=100)
    rate = models.FloatField()
    created_by = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_by = models.IntegerField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'C_DISCOUNT'


auditlog.register(Category)
auditlog.register(Discount)

configuration/forms.py
from django import forms
from .models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ('created_by', 'created_date', 'updated_by', 'updated_date',)
        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}, ),
            "type": forms.TextInput(attrs={'class': 'form-control'}, ),
        }


class DiscountForm(forms.ModelForm):
    class Meta:
        model = Discount
        fields = '__all__'
        exclude = ('created_by', 'created_date', 'updated_by', 'updated_date',)
        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}, ),
            "rate": forms.NumberInput(attrs={'class': 'form-control'}, ),
        }

configuration/views.py
from django.urls import reverse_lazy
from account.decorators import *
from .forms import *
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from datetime import datetime
from django.utils.decorators import method_decorator


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class CategoryListView(ListView):
    model = Category
    template_name = 'configuration/category_list.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'configuration/category_form.html'
    success_url = reverse_lazy('configuration:CategoryListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            item.created_date = datetime.today()
            item.created_by = self.request.session['id']
            item.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(CategoryCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(CategoryCreateView, self).form_invalid(form)


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'configuration/category_form.html'
    success_url = reverse_lazy('configuration:CategoryListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            item.updated_date = datetime.today()
            item.updated_by = self.request.session['id']
            item.save()
            messages.success(self.request, 'Data Successfully Updated')
            return super(CategoryUpdateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(CategoryUpdateView, self).form_invalid(form)


@login_required("logged_in", 'account:login')
@access_permission_required
def CategoryDeleteView(request, id):
    Category.objects.get(pk=id).delete()
    messages.error(request, 'Data Successfully Deleted')
    return redirect('configuration:CategoryListView')


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class DiscountListView(ListView):
    model = Discount
    template_name = 'configuration/discount_list.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(DiscountListView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class DiscountCreateView(CreateView):
    model = Discount
    form_class = DiscountForm
    template_name = 'configuration/discount_form.html'
    success_url = reverse_lazy('configuration:DiscountListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(DiscountCreateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        context['form'] = self.form_class
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            item.created_date = datetime.today()
            item.created_by = self.request.session['id']
            item.save()
            messages.success(self.request, 'Data Successfully Saved')
            return super(DiscountCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(DiscountCreateView, self).form_invalid(form)


@method_decorator(login_required("logged_in", 'account:login'), name='dispatch')
@method_decorator(access_permission_required, name='dispatch')
class DiscountUpdateView(UpdateView):
    model = Discount
    form_class = DiscountForm
    template_name = 'configuration/discount_form.html'
    success_url = reverse_lazy('configuration:DiscountListView')

    def get_context_data(self, **kwargs):
        userdata = {
            'user_id': self.request.session['id'],
            'username': self.request.session['username'],
            'language': self.request.session['language'],
            'urls': self.request.session['urls'],
        }
        context = super(DiscountUpdateView, self).get_context_data(**kwargs)
        context['data'] = userdata
        return context

    def form_valid(self, form):
        if form.is_valid:
            item = form.save(commit=False)
            item.updated_date = datetime.today()
            item.updated_by = self.request.session['id']
            item.save()
            messages.success(self.request, 'Data Successfully Updated')
            return super(DiscountUpdateView, self).form_valid(form)
        else:
            messages.error(self.request, 'invalid')
            return super(DiscountUpdateView, self).form_invalid(form)


@login_required("logged_in", 'account:login')
@access_permission_required
def DiscountDeleteView(request, id):
    Discount.objects.get(pk=id).delete()
    messages.error(request, 'Data Successfully Deleted')
    return redirect('configuration:DiscountListView')

templates/configuration/category_form.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2">
                                {% if data.language == "Eng" %}
                                    Product Category Form
                                {% else %}
                                    পণ্য বিভাগ ফর্ম
                                {% endif %}
                            </h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="" class="col s12" method="post" enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        {% for field in form %}
                                            <div class="input-field col s12">
                                                {{ field }}
                                                <label for="{{ field.id_for_label }}">{{ field.label }} <span
                                                        class="text-danger">*</span></label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <a href="{% url 'configuration:CategoryListView' %}"
                                                   class="btn waves-effect waves-light brown"><i
                                                        class="mdi-content-clear left"></i>
                                                    {% if data.language == "Eng" %}
                                                        Cancel
                                                    {% else %}
                                                        বাতিল করুন
                                                    {% endif %}
                                                </a>
                                                <button class="btn cyan waves-effect waves-light right" type="submit"
                                                        name="action">
                                                    {% if data.language == "Eng" %}
                                                        Submit
                                                    {% else %}
                                                        দাখিল করুন
                                                    {% endif %}
                                                    <i class="mdi-content-send right"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/configuration/category_list.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="table-datatables">
                <div class="row">
                    <div>
                        <h4 class="header">
                            {% if data.language == "Eng" %}
                                Product Category List
                            {% else %}
                                পণ্য বিভাগ লিস্ট
                            {% endif %}
                        </h4>
                    </div>
                    <div style="float: right">
                        <a href="{% url 'configuration:CategoryCreateView' %}"
                           class="btn waves-effect waves-light light-green darken-4"><i
                                class="mdi-content-add left"></i>
                            {% if data.language == "Eng" %}
                                Add Product Category
                            {% else %}
                                পণ্য বিভাগ ফর্ম
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="divider"></div>
                <div class="row">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S/L</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for each in items %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ each.name }}</td>
                                <td>{{ each.type }}</td>
                                <td>
                                    <a href="{% url 'configuration:CategoryUpdateView' each.id %}"
                                       class="btn-floating waves-effect waves-light deep-orange"><i
                                            class="mdi-editor-mode-edit"></i></a>
                                    <a href="#" id="del_btn" name="{{ each.id }}"
                                       class="btn-floating waves-effect waves-light red"><i
                                            class="mdi-action-delete"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).on('click', '#del_btn', function (event) {
            var url = "{% url 'configuration:CategoryDeleteView' 123 %}";
            var id = $(this).attr('name');
            event.preventDefault();
            confirmMessage(url, id);
        });

        function confirmMessage(url, id) {
            swal({
                    title: "Delete Request",
                    text: "Are you sure want to delete ?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes",
                    cancelButtonText: "No",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function (isConfirm) {
                    if (!(isConfirm)) {
                        swal("Operation Cancelled", "...");
                    } else {
                        document.location.href = url.replace('123', id);
                    }
                });
        }
    </script>

{% endblock %}

templates/configuration/discount_form.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l3"><p></p></div>
                    <div class="col s12 m12 l6">
                        <div class="card-panel">
                            <h4 class="header2">
                                {% if data.language == "Eng" %}
                                    Discount Form
                                {% else %}
                                    ডিসকাউনট ফর্ম
                                {% endif %}
                            </h4>
                            <div class="divider"></div>
                            <div class="row">
                                <form action="" class="col s12" method="post" enctype="multipart/form-data"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <div class="row">
                                        {% for field in form %}
                                            <div class="input-field col s12">
                                                {{ field }}
                                                <label for="{{ field.id_for_label }}">{{ field.label }} <span
                                                        class="text-danger">*</span></label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="row">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <a href="{% url 'configuration:DiscountListView' %}"
                                                   class="btn waves-effect waves-light brown"></i>
                                                    {% if data.language == "Eng" %}
                                                        Cancel
                                                    {% else %}
                                                        বাতিল করুন
                                                    {% endif %}
                                                </a>
                                                <button class="btn cyan waves-effect waves-light right" type="submit"
                                                        name="action">
                                                    {% if data.language == "Eng" %}
                                                        Submit
                                                    {% else %}
                                                        দাখিল করুন
                                                    {% endif %}
                                                    <i class="mdi-content-send right"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/configuration/discount_list.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level_tag == 'error' %}
                    <div id="card-alert" class="card red lighten-5">
                        <div class="card-content red-text">
                            <p><strong>{{ message.message }}</strong></p>
                        </div>
                    </div>
                {% elif message.level_tag == 'success' %}
                    <div id="card-alert" class="card green lighten-5">
                        <div class="card-content green-text">
                            <p>{{ message.message }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <div class="section">
            <div id="table-datatables">
                <div class="row">
                    <div>
                        <h4 class="header">
                            {% if data.language == "Eng" %}
                                Discount List
                            {% else %}
                                ডিসকাউনট লিস্ট
                            {% endif %}
                        </h4>
                    </div>
                    <div style="float: right">
                        <a href="{% url 'configuration:DiscountCreateView' %}"
                           class="btn waves-effect waves-light light-green darken-4"><i
                                class="mdi-content-add left"></i>
                            {% if data.language == "Eng" %}
                                Add Discount
                            {% else %}
                                ডিসকাউনট ফর্ম
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="divider"></div>
                <div class="row">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S/L</th>
                            <th>Name</th>
                            <th>Rate</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for each in items %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ each.name }}</td>
                                <td>{{ each.rate }}%</td>
                                <td>
                                    <a href="{% url 'configuration:DiscountUpdateView' each.id %}"
                                       class="btn-floating waves-effect waves-light deep-orange"><i
                                            class="mdi-editor-mode-edit"></i></a>
                                    <a href="#" id="del_btn" name="{{ each.id }}"
                                       class="btn-floating waves-effect waves-light red"><i
                                            class="mdi-action-delete"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).on('click', '#del_btn', function (event) {
            var url = "{% url 'configuration:DiscountDeleteView' 123 %}";
            var id = $(this).attr('name');
            event.preventDefault();
            confirmMessage(url, id);
        });

        function confirmMessage(url, id) {
            swal({
                    title: "Delete Request",
                    text: "Are you sure want to delete ?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes",
                    cancelButtonText: "No",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function (isConfirm) {
                    if (!(isConfirm)) {
                        swal("Operation Cancelled", "...");
                    } else {
                        document.location.href = url.replace('123', id);
                    }
                });
        }
    </script>

{% endblock %}